apiVersion: apps/v1
kind: Deployment
metadata:
    name: localizer-deployment
spec:
    selector:
        matchLabels:
            app: localizer
    replicas: 1
    template:
        metadata:
            labels:
                app: localizer
        spec:
            containers:
            - name: localizer
              image: dnmsdocker/localizer:1.0.1
              ports:
                - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  type: LoadBalancer
  name: localizer-service
spec:
  selector:
    app: localizer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080